{% set version = "1.0.5-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maldirppa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MALDIrppa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MALDIrppa/MALDIrppa_{{ version }}.tar.gz
  sha256: a52425965d43e657c8511af54f33322bd132ec082c1a857c6890d0551e689071

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-maldiquant
    - r-lattice
    - r-robustbase
    - r-signal
    - r-wmtsa
  run:
    - r-base
    - r-maldiquant
    - r-lattice
    - r-robustbase
    - r-signal
    - r-wmtsa

test:
  commands:
    - $R -e "library('MALDIrppa')"           # [not win]
    - "\"%R%\" -e \"library('MALDIrppa')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MALDIrppa
  license: GPL-2.0-or-later
  summary: Provides methods for quality control and robust pre-processing and analysis of MALDI mass spectrometry data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: MALDIrppa
# Type: Package
# Title: MALDI Mass Spectrometry Data Robust Pre-Processing and Analysis
# Version: 1.0.1-2
# Date: 2018-11-03
# Author: Javier Palarea-Albaladejo
# Maintainer: Javier Palarea-Albaladejo <javier.palarea@bioss.ac.uk>
# Depends: R (>= 3.2.5), MALDIquant, signal, robustbase, wmtsa, lattice
# ByteCompile: yes
# Description: Provides methods for quality control and robust pre-processing and analysis of MALDI mass spectrometry data.
# License: GPL (>= 2)
# Repository: CRAN
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-11-09 08:12:30 UTC; Japal
# Date/Publication: 2018-11-09 14:20:15 UTC
