travis:
  secure:
    BINSTAR_TOKEN: jfDZZO7TFNBIQlfpkTbZZRYWwpVtBc+tqhZIp3u2svhiunvSOvVK9pwiGA1QPvGxWKa7RPBwMoptlGcugb4f857C4vvmJKCa/J1k+TOr9YPGfEVADX31Bip6LC9Ia+LP+lPd49sDFu+5ir9QwKDjBf1zfZGdJhQ7sbZAjdFE0pS26XSQuGhr8EJxV8v1RPMgVZ8P4V5QY+UGpyNho0iBXioRTY/63Vb7116i7CNi/7lg1BrPBMJ1mHf3+k7OxmgZ1Op9+xIrQNeC4M1JMELBhROVd24v5E/z6/u5MvekoOzfPufQ7uycWKjsWufT/deuCmfA4Vhqn4OpBhlrM86X/j1iWMcfnGVY6nJEriILkiSqTgdkhEqzAShixdxLARCqpOG82BAFrmTrBU8ITRO43u0nhLndj8Bll3lyGkf/vB8ST7EsKsPGn3vwFnSfF++tVukk68I1S36gFyEJFK8vEbUlgiyZ9N2EpvcA9QiJZHi4mt7VWPhYqCDFGtJadzsXTrXfuj53tXPqR8VTQ4mp2+Z3i+hsLkfsUNoms8Yk68g4RNyg4jMwNv5HoHboUx2rdwWJJhur+ehtLSRFWHgVVMVRRDTppQGSP4AMnKBZGfoUkiNfjPrtjDnvDyns5fpLVB0mrjli0fhitCYhsOFzuQlGwBxcpzCYnZRZ7dHC8d4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
